version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - echo update npm...
            - npm install -g n
            - n latest
            - npm update -g npm
            - echo node -v
            - node -v
            - echo npm -v
            - npm -v
            - 'touch .npmignore'
            - 'npm install -g gatsby gatsby-cli'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'gatsby build --profile'
    post_build:
        commands:
            - 'npm run deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/**/*'
        - 'node_modules/**/*'
        - 'public/**/*'
