version: 0.2
CODEBUILD_BUILD_SUCCEEDING: 0
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - 'touch .npmignore'
            - 'npm install -g yarn gatsby gatsby-cli'
    pre_build:
        commands:
            - 'yarn install'
    build:
        commands:
<<<<<<< HEAD
            - 'gatsby build'

    post_build:
        commands:
            - test "$CODEBUILD_BUILD_SUCCEEDING" = "1"
            - 'yarn run deploy'
=======
            - 'n latest'
            - 'npm run build'

    post_build:
        commands:
            - 'npm run deploy'
>>>>>>> new-master-branch
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/**/*'
        - 'node_modules/**/*'
        - 'public/**/*'
