version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby gatsby-cli'
    pre_build:
        commands:
            - 'npm install'
    build:
        - exit_code=0
        commands:
            - 'npm run slim_build'
            - 'echo $exit_code'
            - 'echo $'
    post_build:
        commands:
            - 'npm run deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/**/*'
        - 'node_modules/**/*'
        - 'public/**/*'
