version: 0.2
CODEBUILD_BUILD_SUCCEEDING: 0
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby gatsby-cli'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run slim_build'

    post_build:
        commands:
            - 'echo $'
            - 'CODEBUILD_BUILD_SUCCEEDING:$'
            - 'echo $CODEBUILD_BUILD_SUCCEEDING'
            - test "$CODEBUILD_BUILD_SUCCEEDING" = "1"
            - 'npm run deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/**/*'
        - 'node_modules/**/*'
        - 'public/**/*'
